[project]
name = "my-pipedream-components"
version = "0.0.0"
description = "This workspace manager."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "doc8>=1.1.2",
    "esbonio>=0.16.5",
]

[tool.doc8]
max-line-length = 119
sphinx = false
